name: solana_playground_language
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  uuid: ^3.0.5
  observable: ^0.24.0

  solana_playground_language_generator:
    path: ./packages/solana_playground_language_generator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  build_runner: ^2.1.11
  build_verify: ^3.0.0
  test: ^1.5.1

flutter:
