name: solana_playground_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^3.2.2
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true