name: solana_playground_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  auto_route: ^4.0.1
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  equatable: ^2.0.3
  base_x: ^2.0.0
  dio: ^4.0.6
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^5.0.2
  dotted_border: ^2.0.0+2
  url_launcher: ^6.1.2
  flutter_markdown: ^0.6.10+2
  sliver_tools: ^0.2.6
  flutter_colorpicker: ^1.0.3
  json_annotation: ^4.5.0
  solana: ^0.25.0
  share_plus: ^4.0.8
  path_provider: ^2.0.11
  async: ^2.8.2
  responsive_builder: ^0.4.2
  # localstore: ^1.2.3

  solana_playground_language:
    path: ./packages/solana_playground_language

  solana_playground_runtime:
    path: ./packages/solana_playground_runtime

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^4.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.10

  flutter_lints: ^2.0.1

dependency_overrides:
  analyzer: ^3.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/projects/