name: solana_playground_runtime
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  solana: ^0.25.0
  base_x: ^2.0.0
  solana_playground_language:
    path: ../solana_playground_language

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: