name: solana_playground_language_generator
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  analyzer: '>=2.1.0 <4.0.0'
  build: ^2.3.0
  source_gen: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
